### ISSUE TITLE
Plugin does not work together with `cypress-on-fix`

### ISSUE THREAD

**Issue by csvtuda** [Qytera-Gmbh/cypress-xray-plugin#101]
> So according to this plugin it is possible to create a cucumber report and work with the xray plugin. 
I haven't managed to make it work though.

_Originally posted by @alexviz7 in https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/79#issuecomment-1623374705_

**Comment by alexviz7** [comment]
Hi,

I get an error when I use the cypress-fix plugin
```
Your configFile threw an error from: C:\Projects\cypress.config.ts

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: (0 , cypress_on_fix_1.default) is not a function
    at setupNodeEvents (C:\Projects\trustcenter\frontend\trustcenter\cypress.config.ts:28:17)
    at C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:122:14
    at tryCatcher (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\bluebird\js\release\method.js:39:29)
    at RunPlugins.load (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:119:9)
    at RunPlugins.runSetupNodeEvents (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:59:17)
    at EventEmitter.<anonymous> (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:511:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:511:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at emit (node:internal/child_process:944:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by alexviz7** [comment]
Update:

I fixed the above issue by deleting  `const on = fix(cypressOn);` and the test was executed. However in the end I had the following error 

```
An error was thrown in your plugins file while executing the handler for the after:spec event.
The error we received was:

Error: ENOENT: no such file or directory, open 'C:\Projects\trustcenter\frontend\trustcenter\cypress\cucumber-json\cucumber-messages.ndjson'
```
