### ISSUE TITLE
Cypress not working with v4.0.0 

### ISSUE THREAD

**Issue by alexviz7** [Qytera-Gmbh/cypress-xray-plugin#132]
Thank you first of all for the work you ve done to fix the issues I found.
I installed the latest cypress-xray-plugin version 4.0.0 and after that I had an Error on my cypress config file.

![Screenshot 2023-07-31 114412](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/c7faae9a-9761-4e39-81ad-f4654d9dd059)

Running cypress with the Jira PAT created the following error:

```
Your configFile is invalid: C:\Projects\frontend\cypress.config.ts

It threw an error when required, check the stack trace below:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in C:\Projects\frontend\node_modules\cypress-xray-plugin\package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:259:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:589:9)
    at resolveExports (node:internal/modules/cjs/loader:571:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:645:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1058:27)
    at Function.Module._resolveFilename (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\tsconfig-paths\lib\register.js:75:40)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (C:\Projects\frontend\cypress.config.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module.m._compile (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\ts-node\dist\index.js:857:29)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\ts-node\dist\index.js:859:16)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Function.Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at loadFile (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (C:\Users\AppData\Local\Cypress\Cache\12.8.1\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_require_async_child.js:116:38)
```

**Comment by csvtuda** [comment]
Please make sure to update the import to:

```ts
import {
  addXrayResultUpload,
  configureXrayPlugin,
  syncFeatureFile
} from  "cypress-xray-plugin";
```

(see [changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#400))

**Comment by alexviz7** [comment]
> Please make sure to update the import to:
> 
> ```ts
> import {
>   addXrayResultUpload,
>   configureXrayPlugin,
>   syncFeatureFile
> } from  "cypress-xray-plugin";
> ```
> 
> (see [changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#400))

I have tried that also and I had the following error:
```
Your configFile threw an error from: C:\Projects\frontend\cypress.config.ts

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: Cannot use 'in' operator to search for 'JIRA_ATTACH_VIDEOS' in undefined
    at parse (C:\Projects\frontend\node_modules\cypress-xray-plugin\src\util\parsing.js:61:21)
    at initOptions (C:\Projects\frontend\node_modules\cypress-xray-plugin\src\context.js:21:47)
    at configureXrayPlugin (C:\Projects\frontend\node_modules\cypress-xray-plugin\src\plugin.js:12:45)
    at setupNodeEvents (C:\Projects\frontend\cypress.config.ts:33:28)
```

**Comment by csvtuda** [comment]
Have you updated `configureXrayPlugin()` as well? It now expects the `config` as first parameter:

```ts
async setupNodeEvents(on, config) {
    await configureXrayPlugin(
        config,
        {
            jira: {
                projectKey: "PRJ",         // placeholder value
                url: "https://example.org" // placeholder value
            }
        }
    );
    // ...
}
```

**Comment by alexviz7** [comment]
I changed the code as you proposed and I have now the following error:

```
  Running:  language.feature                                                                (1 of 1)
X [ERROR] Could not resolve "cypress-xray-plugin/register"

    cypress/support/e2e.ts:20:7:
      20 │ import 'cypress-xray-plugin/register';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./register" is not exported by package "cypress-xray-plugin":

    node_modules/cypress-xray-plugin/package.json:30:15:
      30 │     "exports": "./index.js",
         ╵                ~~~~~~~~~~~~

  You can mark the path "cypress-xray-plugin/register" as external to exclude it from the bundle, which will remove this error.


Oops...we found an error preparing this test file:

  > cypress\support\e2e.ts

The error was:

Error: Build failed with 1 error:
cypress/support/e2e.ts:20:7: ERROR: Could not resolve "cypress-xray-plugin/register"
    at failureErrorWithLog (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Projects\frontend\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1046:7)
    at C:\Projects\frontend\node_modules\esbuild\lib\main.js:1075:16
    at responseCallbacks.<computed> (C:\Projects\frontend\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (C:\Projects\frontend\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (C:\Projects\frontend\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:511:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:305:9)

TypeError: Cannot read properties of null (reading 'some')
    at afterSpecHandler (C:\Projects\frontend\node_modules\@badeball\cypress-cucumber-preprocessor\lib\add-cucumber-preprocessor-plugin.js:166:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Projects\frontend\node_modules\cypress-on-fix\index.js:32:20)
```

**Comment by alexviz7** [comment]
Further errors shown on cypress config file:
![Screenshot 2023-07-31 155218](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/4962329c-b5b4-4411-adf2-6962611bed3f)
![Screenshot 2023-07-31 155250](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/57d56a97-06ee-45bb-807e-364555ad62d8)
![Screenshot 2023-07-31 155454](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/9295838/48c69cec-12b4-4679-806d-bc0bced27109)

**Comment by csvtuda** [comment]
Yes, these options don't exist anymore (see [changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#400)):
> 
> - Removed `plugin.overwriteIssueSummary` option
> 
> - Removed `xray.testType` option
> 
> - Removed `jira.createTestIssues` option

**Comment by csvtuda** [comment]
No, this is not possible anymore. It was possible to configure such created issues (summary, ..) when using the normal upload, but it was not possible to configure them using the Cucumber upload. Xray simply does what it wants in this case, unfortunately.

Keeping things as is for the normal upload would have meant adding a whole new set of options for Cucumber specifically and would have overcomplicated the configuration (for me as well as for the users).

The easier option was to simply not allow issue creation anymore. So you either link your tests/scenarios/backgrounds to existing issues, or they will be skipped during upload.

**Comment by alexviz7** [comment]
well for me its a relief not to have to delete the generated tickets after a test run.

**Comment by csvtuda** [comment]
No, if you don't merge the backgrounds, your feature files will not be uploaded anymore, which means that no background issues will be created anymore either.

Regarding the results displayed in a test execution: I'm actually unsure. I think in the worst case you might see a warning like "executed steps don't match steps of test issue".

**Comment by alexviz7** [comment]
Ok thanks again for your help. Just don't forget to document this on your plugin configuration documentation, for others to see.

**Comment by csvtuda** [comment]
Yes, I will make sure to add a note somewhere. I will try it out myself later, just to see what actually happens. I will close this issue, the `/register` issue will be tracked in #133.
