### ISSUE TITLE
Could not resolve `cypress-xray-plugin/register`

### ISSUE THREAD

**Issue by csvtuda** [Qytera-Gmbh/cypress-xray-plugin#133]
I changed the code as you proposed and I have now the following error when running:

```
  Running:  language.feature                                                                (1 of 1)
X [ERROR] Could not resolve "cypress-xray-plugin/register"

    cypress/support/e2e.ts:20:7:
      20 │ import 'cypress-xray-plugin/register';
         ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./register" is not exported by package "cypress-xray-plugin":

    node_modules/cypress-xray-plugin/package.json:30:15:
      30 │     "exports": "./index.js",
         ╵                ~~~~~~~~~~~~

  You can mark the path "cypress-xray-plugin/register" as external to exclude it from the bundle, which will remove this error.


Oops...we found an error preparing this test file:

  > cypress\support\e2e.ts

The error was:

Error: Build failed with 1 error:
cypress/support/e2e.ts:20:7: ERROR: Could not resolve "cypress-xray-plugin/register"
    at failureErrorWithLog (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1636:15)
    at C:\Projects\frontend\node_modules\esbuild\lib\main.js:1048:25
    at runOnEndCallbacks (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1471:45)
    at buildResponseToResult (C:\Projects\frontend\node_modules\esbuild\lib\main.js:1046:7)
    at C:\Projects\frontend\node_modules\esbuild\lib\main.js:1075:16
    at responseCallbacks.<computed> (C:\Projects\frontend\node_modules\esbuild\lib\main.js:697:9)
    at handleIncomingPacket (C:\Projects\frontend\node_modules\esbuild\lib\main.js:752:9)
    at Socket.readFromStdout (C:\Projects\frontend\node_modules\esbuild\lib\main.js:673:7)
    at Socket.emit (node:events:511:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:332:12)
    at readableAddChunk (node:internal/streams/readable:305:9)

TypeError: Cannot read properties of null (reading 'some')
    at afterSpecHandler (C:\Projects\frontend\node_modules\@badeball\cypress-cucumber-preprocessor\lib\add-cucumber-preprocessor-plugin.js:166:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (C:\Projects\frontend\node_modules\cypress-on-fix\index.js:32:20)
```

_Originally posted by @alexviz7 in https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/132#issuecomment-1657977198_

**Comment by csvtuda** [comment]
@alexviz7 This issue should be fixed in `4.0.1`, feel free to try it out.

**Comment by alexviz7** [comment]
Ok it works with /register too now and no error shown.

**Comment by caique-raidiam** [comment]
@csvtuda I'm getting this problem in 4.0.1 version, what should I do?

**Comment by caique-raidiam** [comment]
Works in 3.3.3

**Comment by caique-raidiam** [comment]
Using `import "cypress-xray-plugin/plugin";` in e2e.js with 4.0.1 version works, should I use this way?

**Comment by csvtuda** [comment]
@caique-raidiam just remove the import altogether. It does not do anything and I am not planning on using the app events I could define in there.
