### ISSUE TITLE
Using multiple Cypress Config Files leeds to Error `Your configfile is invalid`

### ISSUE THREAD

**Issue by chris-wgg** [Qytera-Gmbh/cypress-xray-plugin#195]
Hello together,

We use the plugin with Cypress and several configfiles.
since the upgrade to Cypress V13+ together with Cypress-Xray V5+ we get the error message that our configfile is invalid.

Concrete Versions used here:

    "cypress": "^13.2.0",
    "cypress-xray-plugin": "^5.0.0"

The Error Message:

```console
Your configFile is invalid: /Users/christoph/projekte/cypress-patch-management/cypress.xray-config.js
It threw an error when required, check the stack trace below:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in /Users/.../node_modules/cypress-xray-plugin/package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/christoph/projekte/cypress-patch-management/cypress.xray-config.js:2:54)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at loadFile (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:513:28)
    at process.<anonymous> (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
   
```

We use multiple configfiles to control the reported output.
One configfile is specifically responsible for the synchronisation of the tests with Xray. Another is used locally and another reports JUnit results in the pipeline.

This is our specific config for Xray sync:
```js
//cypress.xray-config.js 
const { defineConfig } = require('cypress');
const { addXrayResultUpload, configureXrayPlugin } = require('cypress-xray-plugin/plugin');

module.exports = defineConfig({
  viewportWidth: 1920,
  viewportHeight: 1080,
  pageLoadTimeout: 60000,
  defaultCommandTimeout: 10000,
  video: false,
  e2e: {
    baseUrl: 'someURL',
    includeShadowDom: true,
    async setupNodeEvents(on, config) {
      await configureXrayPlugin({
        jira: {
          url: 'myJiraURL',
          projectKey: 'MYPROJ',
          testExecutionIssueKey: 'myTESTEXECUTION',
          testPlanIssueKey: 'myTESTPLAN',
        },
      });
      await addXrayResultUpload(on);
    },
  },
});
```

we execute the cypress test run with this command:
```console
npx cypress run --config-file cypress.xray-config.js --env JIRA_API_TOKEN=$JIRA_API_TOKEN
```

The "default" configfile:

```js
//cypress.config.js
const { defineConfig } = require("cypress");

module.exports = defineConfig({
  trashAssetsBeforeRuns: true,
  e2e: {
    setupNodeEvents(on, config) {
      // implement node event listeners here
    },
    video: false
  },
});

```

With using 
    "cypress": "12.17.3",
    "cypress-xray-plugin": "3.3.3"
    
  Everything is working fine as expected

**Comment by csvtuda** [comment]
Hey @chris-wgg,

thanks for raising this issue, I actually didn't know Cypress supports multiple config files, so today I learned 👍 

However, I think the issue is that you're using an outdated cypress-xray-plugin import. [Version 4](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#400) removed the `/plugin` part from all imports.

Can you check if replacing all imports as follows already solves your problem?

Please replace:

  ```ts
  const { addXrayResultUpload, configureXrayPlugin } = require('cypress-xray-plugin/plugin');
  ```

with:

  ```ts
const { addXrayResultUpload, configureXrayPlugin } = require('cypress-xray-plugin');
  ```

**Comment by chris-wgg** [comment]
Hi @csvtuda 

thank you for your Answer and the new way to import the plugin.

I´ve changed the import, but get another error:

```console
Your configFile threw an error from: /Users/christoph/projekte/cypress-patch-management/cypress.xray-config.js

The error was thrown while executing your e2e.setupNodeEvents() function:

TypeError: Cannot use 'in' operator to search for 'JIRA_ATTACH_VIDEOS' in undefined
    at parse (/Users/christoph/projekte/cypress-patch-management/node_modules/cypress-xray-plugin/src/util/parsing.js:61:21)
    at initOptions (/Users/christoph/projekte/cypress-patch-management/node_modules/cypress-xray-plugin/src/context.js:18:47)
    at configureXrayPlugin (/Users/christoph/projekte/cypress-patch-management/node_modules/cypress-xray-plugin/src/plugin.js:12:45)
    at setupNodeEvents (/Users/christoph/projekte/cypress-patch-management/cypress.xray-config.js:14:13)
    at /Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:122:14
    at tryCatcher (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.attempt.Promise.try (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/node_modules/bluebird/js/release/method.js:39:29)
    at RunPlugins.load (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:119:9)
    at RunPlugins.runSetupNodeEvents (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_plugins.js:59:17)
    at EventEmitter.<anonymous> (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/child/run_require_async_child.js:185:22)
    at EventEmitter.emit (node:events:513:28)
    at process.<anonymous> (/Users/christoph/Library/Caches/Cypress/13.2.0/Cypress.app/Contents/Resources/app/packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:937:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Than I´ve tried to set the JIRA_ATTACH_VIDEOS var to 'false' in my config file:
```js
//cypress.xray-config.js 
const { defineConfig } = require('cypress');
const { addXrayResultUpload, configureXrayPlugin } = require('cypress-xray-plugin/plugin');

module.exports = defineConfig({
  viewportWidth: 1920,
  viewportHeight: 1080,
  pageLoadTimeout: 60000,
  defaultCommandTimeout: 10000,
  video: false,
  e2e: {
    baseUrl: 'someURL',
    includeShadowDom: true,
    async setupNodeEvents(on, config) {
      await configureXrayPlugin({
        jira: {
          url: 'myJiraURL',
          projectKey: 'MYPROJ',
          testExecutionIssueKey: 'myTESTEXECUTION',
          testPlanIssueKey: 'myTESTPLAN',
          attachVideos: false,
        },
      });
      await addXrayResultUpload(on);
    },
  },
});
```

But I got the same error I added above after update the import

**Comment by csvtuda** [comment]
I think you also need to change the configuration method call, it expects the cypress configuration to be passed as first argument (also introduced in 4.0.0):

```ts
await configureXrayPlugin(
  config, // here
  {
    jira: {
      url: 'myJiraURL',
      projectKey: 'MYPROJ',
      testExecutionIssueKey: 'myTESTEXECUTION',
      testPlanIssueKey: 'myTESTPLAN',
      attachVideos: false,
    },
  }
);
```

**Comment by chris-wgg** [comment]
This solves the issue,
Thank you and thanks again for the verry fast feedback!
