### ISSUE TITLE
Failed to import execution: Request failed with status code 400

### ISSUE THREAD

**Issue by PatriceKabengele** [Qytera-Gmbh/cypress-xray-plugin#369]
### Description

```
{
   "error":{
      "message":"Request failed with status code 400",
      "name":"AxiosError",
      "stack":"AxiosError: Request failed with status code 400\n    at settle (/Users/***/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:2015:12)\n    at IncomingMessage.handleStreamEnd (/Users/***/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:3131:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1376:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/Users/***/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async XrayClientCloud.importExecution (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/client/xray/xray-client.js:25:34)\n    at async ImportExecutionCypressCommand.computeResult (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/util/commands/xray/import-execution-cypress-command.js:13:16)\n    at async ImportExecutionCypressCommand.compute (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/command.js:87:16)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:74:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.execute (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:40:9)\n    at async Object.handler (/Users/***/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/plugin.js:115:13)",
      "config":{
         "transitional":{
            "silentJSONParsing":true,
            "forcedJSONParsing":true,
            "clarifyTimeoutError":false
         },
         "adapter":[
            "xhr",
            "http",
            "fetch"
         ],
         "transformRequest":[
            null
         ],
         "transformResponse":[
            null
         ],
         "timeout":0,
         "xsrfCookieName":"XSRF-TOKEN",
         "xsrfHeaderName":"X-XSRF-TOKEN",
         "maxContentLength":-1,
         "maxBodyLength":-1,
         "env":{
            
         },
         "headers":{
            "Accept":"application/json, text/plain, */*",
            "Content-Type":"application/json",
            "Authorization":"Bearer ***",
            "User-Agent":"axios/1.7.3",
            "Content-Length":"667",
            "Accept-Encoding":"gzip, compress, deflate, br"
         },
         "method":"post",
         "url":"https://xray.cloud.getxray.app/api/v2/import/execution",
         "data":"{\"info\":{\"description\":\"Cypress version: 13.13.0\\nBrowser: chrome (127.0.6533.89)\",\"finishDate\":\"2024-08-05T13:41:30Z\",\"project\":\"ET\",\"startDate\":\"2024-08-05T13:40:55Z\",\"summary\":\"Execution Results [1722865255968]\",\"testPlanKey\":\"ET-17283\"},\"tests\":[{\"finish\":\"2024-08-05T13:41:06Z\",\"start\":\"2024-08-05T13:40:55Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17266\"},{\"finish\":\"2024-08-05T13:41:14Z\",\"start\":\"2024-08-05T13:41:06Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17267\"},{\"finish\":\"2024-08-05T13:41:21Z\",\"start\":\"2024-08-05T13:41:14Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17268\"},{\"finish\":\"2024-08-05T13:41:29Z\",\"start\":\"2024-08-05T13:41:21Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17269\"}]}"
      },
      "code":"ERR_BAD_REQUEST",
      "status":400
   },
   "response":{
      "error":"Error creating Test Execution - Issue create failed!"
   }
}
```

### Cypress version

13.13.0

### Plugin version

7.1.0

### Jira/Xray type

Cloud

### Configuration

```ts
e2e: {
    async setupNodeEvents(on, config) {
      await configureXrayPlugin(on, config, {
        jira: {
          projectKey: '**',
          url: 'https://***.atlassian.net/',
          fields: {
            summary: 'summary'
          }
        },
        xray: {
          status: {
            pending: 'PENDING',
            skipped: 'SKIPPED'
          },
          uploadResults: true
        }
      });
    },
  },
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hi @PatriceKabengele,

> Error creating Test Execution - Issue create failed!

It sounds like:

- your Jira project requires additional information on issue creation (mandatory assignee, ...)
- the user whose credentials you're using may not have permissions to create test execution issues

Can you check if you can manually create a test execution issue in the `ET` project with nothing but the following fields set?

- description: "Cypress version: 13.13.0\\nBrowser: chrome (127.0.6533.89)",
- summary: "Execution Results [1722865255968]",
- testPlanKey: "ET-17283"

Make sure to not assign the issue to anyone and to use the credentials you've provided to the plugin.

**Comment by PatriceKabengele** [comment]
Thank for your reply @csvtuda, indeed I have a mandatory field called "Domaine" (customfield_10202)

**Comment by csvtuda** [comment]
Okay, the bad news is that with the current version it is not possible to define custom/arbitrary fields for the created test executions. But the good news is that I'm actually working on exactly this right now, so hopefully your issue will be fixed in the next release.

**Comment by PatriceKabengele** [comment]
Great thank you, I'll wait for next release.

**Comment by PatriceKabengele** [comment]
@csvtuda I've removed the mandatory field but I've still the following error: 
```
{
   "error":{
      "message":"Request failed with status code 400",
      "name":"AxiosError",
      "stack":"AxiosError: Request failed with status code 400\n    at settle (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:2015:12)\n    at IncomingMessage.handleStreamEnd (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:3131:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1376:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async XrayClientCloud.importExecution (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/client/xray/xray-client.js:25:34)\n    at async ImportExecutionCypressCommand.computeResult (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/util/commands/xray/import-execution-cypress-command.js:13:16)\n    at async ImportExecutionCypressCommand.compute (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/command.js:87:16)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:74:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.execute (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:40:9)\n    at async Object.handler (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/plugin.js:115:13)",
      "config":{
         "transitional":{
            "silentJSONParsing":true,
            "forcedJSONParsing":true,
            "clarifyTimeoutError":false
         },
         "adapter":[
            "xhr",
            "http",
            "fetch"
         ],
         "transformRequest":[
            null
         ],
         "transformResponse":[
            null
         ],
         "timeout":0,
         "xsrfCookieName":"XSRF-TOKEN",
         "xsrfHeaderName":"X-XSRF-TOKEN",
         "maxContentLength":-1,
         "maxBodyLength":-1,
         "env":{
            
         },
         "headers":{
            "Accept":"application/json, text/plain, */*",
            "Content-Type":"application/json",
            "Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5hbnQiOiIyZTdlMGRhYy1kYWNjLTMzNGYtOGFhNy1hMWM1OTQ2NmUzNTciLCJhY2NvdW50SWQiOiI3MTIwMjA6Mzk2ZjYxODYtYTM1NS00OTE2LTliYzEtNTgyZWUxNzBlYzQ5IiwiaXNYZWEiOmZhbHNlLCJpYXQiOjE3MjI5NTgzNDYsImV4cCI6MTcyMzA0NDc0NiwiYXVkIjoiQzY1NjI0OUZCMEQ5NEYyQUIzNDdGQzlGNzBDMTQ0OEUiLCJpc3MiOiJjb20ueHBhbmRpdC5wbHVnaW5zLnhyYXkiLCJzdWIiOiJDNjU2MjQ5RkIwRDk0RjJBQjM0N0ZDOUY3MEMxNDQ4RSJ9.2A_pSv96hp0zrgeMb0XQNnf-EdsiyQLvoQSf_Gy7nlQ",
            "User-Agent":"axios/1.7.3",
            "Content-Length":"667",
            "Accept-Encoding":"gzip, compress, deflate, br"
         },
         "method":"post",
         "url":"https://xray.cloud.getxray.app/api/v2/import/execution",
         "data":"{\"info\":{\"description\":\"Cypress version: 13.13.0\\nBrowser: chrome (127.0.6533.89)\",\"finishDate\":\"2024-08-06T15:33:11Z\",\"project\":\"ET\",\"startDate\":\"2024-08-06T15:32:29Z\",\"summary\":\"Execution Results [1722958349531]\",\"testPlanKey\":\"ET-17283\"},\"tests\":[{\"finish\":\"2024-08-06T15:32:39Z\",\"start\":\"2024-08-06T15:32:29Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17266\"},{\"finish\":\"2024-08-06T15:32:47Z\",\"start\":\"2024-08-06T15:32:39Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17267\"},{\"finish\":\"2024-08-06T15:33:02Z\",\"start\":\"2024-08-06T15:32:54Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17268\"},{\"finish\":\"2024-08-06T15:33:09Z\",\"start\":\"2024-08-06T15:33:02Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17269\"}]}"
      },
      "code":"ERR_BAD_REQUEST",
      "status":400
   },
   "response":{
      "error":"Error creating Test Execution - Issue create failed!"
   }
}
```

**Comment by PatriceKabengele** [comment]
@csvtuda I've removed the mandatory field but I still have an error. I've verified my user have credentials to create issued
```
{
   "error":{
      "message":"Request failed with status code 400",
      "name":"AxiosError",
      "stack":"AxiosError: Request failed with status code 400\n    at settle (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:2015:12)\n    at IncomingMessage.handleStreamEnd (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:3131:11)\n    at IncomingMessage.emit (node:events:526:35)\n    at endReadableNT (node:internal/streams/readable:1376:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Axios.request (/Users/**/Workspace/Cypress/zest-e2e/node_modules/axios/dist/node/axios.cjs:4262:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async XrayClientCloud.importExecution (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/client/xray/xray-client.js:25:34)\n    at async ImportExecutionCypressCommand.computeResult (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/util/commands/xray/import-execution-cypress-command.js:13:16)\n    at async ImportExecutionCypressCommand.compute (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/hooks/command.js:87:16)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:74:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.executeFollowedBySuccessors (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:89:13)\n    at async Promise.all (index 0)\n    at async ExecutableGraph.execute (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/util/graph/executable-graph.js:40:9)\n    at async Object.handler (/Users/**/Workspace/Cypress/zest-e2e/node_modules/cypress-xray-plugin/src/plugin.js:115:13)",
      "config":{
         "transitional":{
            "silentJSONParsing":true,
            "forcedJSONParsing":true,
            "clarifyTimeoutError":false
         },
         "adapter":[
            "xhr",
            "http",
            "fetch"
         ],
         "transformRequest":[
            null
         ],
         "transformResponse":[
            null
         ],
         "timeout":0,
         "xsrfCookieName":"XSRF-TOKEN",
         "xsrfHeaderName":"X-XSRF-TOKEN",
         "maxContentLength":-1,
         "maxBodyLength":-1,
         "env":{
            
         },
         "headers":{
            "Accept":"application/json, text/plain, */*",
            "Content-Type":"application/json",
            "Authorization":"Bearer **",
            "User-Agent":"axios/1.7.3",
            "Content-Length":"667",
            "Accept-Encoding":"gzip, compress, deflate, br"
         },
         "method":"post",
         "url":"https://xray.cloud.getxray.app/api/v2/import/execution",
         "data":"{\"info\":{\"description\":\"Cypress version: 13.13.0\\nBrowser: chrome (127.0.6533.89)\",\"finishDate\":\"2024-08-06T15:33:11Z\",\"project\":\"ET\",\"startDate\":\"2024-08-06T15:32:29Z\",\"summary\":\"Execution Results [1722958349531]\",\"testPlanKey\":\"ET-17283\"},\"tests\":[{\"finish\":\"2024-08-06T15:32:39Z\",\"start\":\"2024-08-06T15:32:29Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17266\"},{\"finish\":\"2024-08-06T15:32:47Z\",\"start\":\"2024-08-06T15:32:39Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17267\"},{\"finish\":\"2024-08-06T15:33:02Z\",\"start\":\"2024-08-06T15:32:54Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17268\"},{\"finish\":\"2024-08-06T15:33:09Z\",\"start\":\"2024-08-06T15:33:02Z\",\"status\":\"PASSED\",\"testKey\":\"ET-17269\"}]}"
      },
      "code":"ERR_BAD_REQUEST",
      "status":400
   },
   "response":{
      "error":"Error creating Test Execution - Issue create failed!"
   }
}
```

**Comment by csvtuda** [comment]
That's weird, can you try to directly create the test execution issue yourself through Jira's API?

```sh


curl \
--silent \
--user 'JIRA_USERNAME:JIRA_API_TOKEN' \
--location 'https://JIRA_URL.atlassian.net/rest/api/3/issue' \
--header 'Content-Type: application/json' \
--data '{
    "fields": {
        "summary": "Execution Results [1722865255968]",
	"description": {
	    "type": "doc",
	    "version": 1,
	    "content": [
                {
                    "type": "paragraph",
                    "content": [
                        {
                            "type": "text",
                            "text": "Cypress version: 13.13.0"
                        },
                        {
                            "type": "hardBreak"
                        },
                        {
                            "type": "text",
                            "text": "Browser: chrome (127.0.6533.89)"
                        }
                    ]
                }
            ]
        },
        "project": {
            "key": "JIRA_PROJECT_KEY"
        },
        "issuetype": {
            "name": "Test Execution"
        }
    }
}'
```

You will need to replace the following placeholders:
- JIRA_USERNAME
- JIRA_API_TOKEN
- JIRA_URL
- JIRA_PROJECT_KEY
- `Test Execution` as the issue type you want to create with a translated name if you're not using English issues

**Comment by PatriceKabengele** [comment]
Yes I had an output like yours, I'll open a support ticket

**Comment by csvtuda** [comment]
Thanks, please let me know if there is anything that comes out of this that I can do to help resolve the issue.

**Comment by PatriceKabengele** [comment]
The support asked me 

> Can you please use prefix eu. or au. or us and let us know if that works.
> 
> For example https://eu.xray.cloud.getxray.app/api/v2/import/execution
> 
> Looking forward to hearing from you.

**Comment by csvtuda** [comment]
I could add Xray cloud URL configurability to upcoming versions, but I think you can quickly try it out yourself without having to wait for new versions.

You can simply edit the following line in [`node_modules/cypress-xray-plugin/src/client/xray/xray-client-cloud.js`](https://www.npmjs.com/package/cypress-xray-plugin?activeTab=code) and try running your tests again:

```diff
    /**
     * The URLs of Xray's Cloud API.
     * Note: API v1 would also work, but let's stick to the more recent one.
     */
-   static URL = "https://xray.cloud.getxray.app/api/v2";
+   static URL = "https://eu.xray.cloud.getxray.app/api/v2";
    static URL_GRAPHQL = `${XrayClientCloud.URL}/graphql`;
    static GRAPHQL_LIMIT = 100;
```

**Comment by PatriceKabengele** [comment]
thank you for the reply, I tried to change the url in xray-client-cloud file like you said but it failed to authenticate
 
> Failed to establish communication with Xray: https://eu.xray.cloud.getxray.app/api/v2/authenticate

**Comment by csvtuda** [comment]
I think you need to try the different subdomains. `eu` did not work for me either (`"401: Xray data is another region"`), but `us` worked.

**Comment by PatriceKabengele** [comment]
i tried `fr` and `us`, but only us work. Maybe I should report it to xray support?

**Comment by csvtuda** [comment]
Yes please. Their [documentation](https://docs.getxray.app/display/XRAYCLOUD/REST+API) clearly states the following:

> [!NOTE]
> The REST API base URL for all endpoints is https://xray.cloud.getxray.app/.

So I'm curious why you need to prefix it with `us`.

**Comment by PatriceKabengele** [comment]
I'll keep you posted

**Comment by csvtuda** [comment]
Hey @PatriceKabengele,

in the meantime I have released version [7.2.0](https://www.npmjs.com/package/cypress-xray-plugin/v/7.2.0) ([changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#720)). You can now specify [arbitrary fields](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissue) for the test execution issues, e.g.:

```js
await configureXrayPlugin(on, config, {
    jira: {
        testExecutionIssue: {
            key: "PRJ-16",
            fields: {
                summary: "My execution issue summary",
                description: "My execution issue description",
                assignee: {
                    name: "cool.turtle@company.com"
                },
                customfield_12345: "Sprint 17"
            }
        }
    },
});
```

Maybe this could also solve your issue already?

**Comment by PatriceKabengele** [comment]
Hello @csvtuda, 
I deleted my API Key (id Client and secret) and created a new one on Jira UI. And it work now.

**Comment by csvtuda** [comment]
@PatriceKabengele well this was an unexpected solution. Glad to hear that 😃

**Comment by PatriceKabengele** [comment]
thanks for your help 🙏🏽
